---
pipeline: analysis
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: false
    file: <metadata file name>
    merge_column: <Column to merge on>
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
  min_cells: 1
normalize_negcon:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
  min_cells: 1
feature_select:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
  min_cells: 1
feature_select_negcon:
  perform: false
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
  min_cells: 1
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2026_01_05_Batch_20
plates:
  - name: 2025_11_04_B20P1T1
    process: true
  - name: 2025_11_04_B20P1T2
    process: true
  - name: 2025_11_05_B20P1T3
    process: true
  - name: 2025_11_04_B20P1T4
    process: true
process: true
---
batch: 2026_01_05_Batch_21
plates:
  - name: 2025_11_05_B21P1T1
    process: true
  - name: 2025_11_06_B21P1T3
    process: true
  - name: 2025_11_07_B21P1T2
    process: true
  - name: 2025_11_07_B21P1T4
    process: true
process: true

